# Generated by Django 5.2.1 on 2025-05-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='category_slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
