# Generated by Django 5.2.1 on 2025-05-30 10:54

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productcategory_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='category_image',
            field=models.FileField(upload_to='categories/', validators=[products.models.validate_image_or_svg]),
        ),
    ]
