# Generated by Django 5.2.1 on 2025-05-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productcategory_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='category_slug',
            field=models.SlugField(unique=True),
        ),
    ]
