# Generated by Django 5.2.1 on 2025-05-30 20:42

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='products/icons/', validators=[products.models.validate_image_or_svg]),
        ),
        migrations.AddField(
            model_name='product',
            name='is_slider_item',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
