# Generated by Django 5.2.1 on 2025-05-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_icon_product_is_slider_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_sub_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
