# Generated by Django 5.2.1 on 2025-05-30 20:56

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_product_sub_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='products/icons/', validators=[products.models.validate_image_or_svg]),
        ),
    ]
