# Generated by Django 5.2.1 on 2025-05-30 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_slider_item',
            new_name='is_slider',
        ),
    ]
