# Generated by Django 5.2.1 on 2025-05-30 21:54

import django.utils.timezone
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poster',
            name='is_footer_poster',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poster',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='poster',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='posters/icons/', validators=[products.models.validate_image_or_svg]),
        ),
    ]
