# Generated by Django 5.2.1 on 2025-05-30 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_colorproduct_remove_product_color_product_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorproduct',
            name='code_color',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
