# Generated by Django 5.2.1 on 2025-05-31 01:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_colorproduct_code_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
